const os = require('os');
const shell = require('shelljs');
const figlet = require('figlet');

figlet('JSTE FRAMEWORK', function (err, data) {
    console.log(data);
    console.log(' Starting building Jste Framework ');
    shell.cd('build');
    shell.rm('-rf', '*');
    shell.mkdir('minified', 'compressed');
    console.log(' Vulcanizing the framework files in to one HTML file ');
    shell.exec('vulcanize ../src/Res.html  --strip-comments --inline-scripts --inline-css > framework.html');
    console.log(' Minifying the framework vulcanized file ');
    shell.exec('html-minifier framework.html --remove-comments --minify-css --minify-js --remove-comments --minify-ur-ls --use-short-doctype > minified/framework.min.html');
    shell.rm('-rf', 'framework.html');
    console.log(' Compresssing the framework minified file ');
    shell.exec('cat minified/framework.min.html | gzip --best > compressed/framework.min.html.gz');
    console.log(' Jste Framework has been built properly ;) ');
    console.log(' ');
    console.log(' Starting building Jste Framework Live Version ');
    console.log(' Vulcanizing the framework files in to one HTML file ');
    shell.exec('vulcanize ../src/Res-LiveVersion.html  --strip-comments --inline-scripts --inline-css > framework-LiveVersion.html');
    console.log(' Minifying the framework vulcanized file ');
    shell.exec('html-minifier framework-LiveVersion.html --remove-comments --minify-css --minify-js --remove-comments --minify-ur-ls --use-short-doctype > minified/framework-LiveVersion.min.html');
    shell.rm('-rf', 'framework-LiveVersion.html');
    console.log(' Compresssing the framework minified file ');
    shell.exec('cat minified/framework-LiveVersion.min.html | gzip --best > compressed/framework-LiveVersion.min.html.gz');
    console.log(' Jste Framework Live Version has been built properly ;) ');
    console.log(' ');
    console.log(' Starting building the BLOB DB manager for Jste Framework Live Version ');
    console.log(' Minifying the BLOB DB manager file ');
    shell.exec('html-minifier ../utils/db-manager.html --remove-comments --minify-css --minify-js --remove-comments --minify-ur-ls --use-short-doctype > minified/db-manager.min.html');
    shell.rm('-rf', 'db-manager.html');
    console.log(' Compresssing the BLOB DB manager minified file ');
    shell.exec('cat minified/db-manager.min.html | gzip --best > compressed/db-manager.min.html.gz');
    console.log(' The BLOB DB manager for Jste Framework Live Version has been built properly ;) ');
});