import 'normalize.css/normalize.css'
import 'material-design-icons/iconfont/material-icons.css'
import '@fortawesome/fontawesome-free/js/all'
import 'core/findBestMatch'
import 'thirdParty/CLD/cld-min'
import 'core/scriptInit'
